<a href="https://colab.research.google.com/github/Sasitorn15/data_viz/blob/main/zeros%2C_ones%2Crandom%2C%E0%B9%80%E0%B8%89%E0%B8%A5%E0%B8%A2%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%9A%E0%B9%89%E0%B8%B2%E0%B8%995.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# zeros, ones, random

In [2]:
import numpy as np #import numpy แล้วตั้งชื่อเป็น np

In [3]:
np. zeros (2)

array([0., 0.])

In [7]:
np. zeros ( (2,3) )

array([[0., 0., 0.],
       [0., 0., 0.]])

#ones

In [9]:
np. ones ( (2,3) )

array([[1., 1., 1.],
       [1., 1., 1.]])

#Matrix Operation (scalar multiplication)

In [11]:
M_one = np. ones((2,3))

2*M_one

array([[2., 2., 2.],
       [2., 2., 2.]])

Random

In [12]:
np. random.rand(3,2)  # uniform random [0,1)

array([[0.99385823, 0.21173874],
       [0.24952421, 0.25307117],
       [0.11044629, 0.02621113]])

In [16]:
np. random.randn(3,2)  # sample from normal distribution mean=0 std=1

array([[-0.43493204,  1.85026035],
       [-0.15817992, -0.19988434],
       [ 0.64362275,  0.67498024]])

In [18]:
np. random.choice([1,2,3,'a','b','c'])

'a'

In [20]:
np. random.choice([1,2,3,28,11,100],size = 2)

array([2, 3])

In [21]:
np. random.choice([1,2,3,28,11,100],size = (2,3),)

array([[ 11,   1,   3],
       [ 28,   1, 100]])

In [22]:
np. random.choice([1,2,3,28,11,100],  size = (2,3), replace=False)

array([[  2,   3,   1],
       [100,  11,  28]])

In [24]:
np. random.choice(['A','B','C','D','F'],size=35, p =  [0.1,0.2,0.4,0.29,0.01] )

array(['C', 'C', 'C', 'B', 'D', 'D', 'C', 'B', 'B', 'B', 'B', 'C', 'D',
       'D', 'D', 'C', 'B', 'D', 'A', 'B', 'B', 'B', 'C', 'A', 'C', 'D',
       'B', 'D', 'D', 'B', 'B', 'D', 'D', 'D', 'C'], dtype='<U1')

## เฉลยHW Matrix Multiplication

In [30]:
def mat_mul(A,B) :
       c = np. onces((A.shap[0],B.shape[1]))#เตรียมขนาดของ matrix ผลลัพธ์
       for  r_a in range(A.shape[0]):
             for  c_b in range(B.shape[1]):
                  for every_element in range(A.shape[1]):
                       C[r_a,c_b] = C[r_a,c_b] + (A[r_a,every_element] * B[every_element,c_b])
       return c

In [31]:
mat1 = np.array([[1,2,3],[4,5,6]])
mat2 = np.array([[7,8],[9,10],[11,12]])

In [36]:
mat_mul(mat1,mat2)

AttributeError: ignored