<a href="https://colab.research.google.com/github/Sasitorn15/data_viz/blob/main/%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%9A%E0%B9%89%E0%B8%B2%E0%B8%995.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

การบ้าน 5

matrix slicing
้HW 5 เขียน function คูณ matrix

แล้ว test กับ matrix

## (2,3)*(3,2)
## (4,4)*(4,1)
## (2,2)*(2,2)

In [16]:
import numpy as np

In [17]:
#Matrix 2*3
mat_A = np.array([[1,4,2],[2,8,7]])
mat_A

array([[1, 4, 2],
       [2, 8, 7]])

In [18]:
#Matrix 3*2
mat_B = np.array([[4,2],[6,8],[2,1]])
mat_B

array([[4, 2],
       [6, 8],
       [2, 1]])

In [19]:
#Matrix 4*4
mat_C = np.array([[1,5,4,3],[5,2,1,4],[9,6,2,4],[1,3,2,4]])
mat_C

array([[1, 5, 4, 3],
       [5, 2, 1, 4],
       [9, 6, 2, 4],
       [1, 3, 2, 4]])

In [20]:
#Matrix 4*1
mat_D = np.array([[1],[4],[5],[7]])
mat_D

array([[1],
       [4],
       [5],
       [7]])

In [21]:

#Matrix 2*2 
mat_E = np.array([[5,1],[4,2]])
mat_E

array([[5, 1],
       [4, 2]])

In [22]:
mat_F = np.array([[1,8],[7,3]])
mat_F

array([[1, 8],
       [7, 3]])

In [37]:
def mul_mat(A, B):
    C = [[0 for row in range(len(B[0]))] for col in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                C[i][j] += A[i][k]*B[k][j]
    r = np.matrix(C)
    return r

In [38]:
mul_mat(mat_A,mat_B)  #ข้อ1

matrix([[32, 36],
        [70, 75]])

In [29]:
mul_mat(mat_C,mat_D)   #ข้อ2

matrix([[62],
        [46],
        [71],
        [51]])

In [39]:
mul_mat(mat_C,mat_D) #ข้อ3

matrix([[62],
        [46],
        [71],
        [51]])